######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 7 20:40:39 2018
######################################################################


QT       += core gui mqtt

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = MQTT_Subcriber
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
